### ISSUE TITLE
Completely Self-Contained Portable Mode?

### ISSUE THREAD

**Issue by Pentaphon** [depler/transmission-vs#2]
Would it be possible to say, put the Transmission-vs folder from a USB stick, insert that stick on any Windows machine you want and run transmission-vs, and then have it download to the same folder so you can unmount the USB stick and take your files with you and not leave any trace (other than firewall prompts, etc) on the Windows machine you used?

I could see many people using transmission-vs that way or at least being able to have a separate torrent client on a Windows machine that could easily be used without any kind of installation whatsoever and keeping everything within 1 folder including the downloads.

**Comment by depler** [comment]
Yes, this is possible. You can start `run_foreground.bat` in transmission folder - that will run transmission as standalone console program without installation. The use web interface `http://localhost:9091/transmission/web/` or `transgui.exe` as client for adding torrents (you will need to change torrent destination folder to USB stick path when starting download)

**Comment by Pentaphon** [comment]
> that will run transmission as standalone console program without installation

What about a silent mode without the console, just running in the background as an exe?

**Comment by depler** [comment]
It doesn't really make sense, because tranmission is a torrent server by design and there is no mechanism to stop it in background from UI client. For this purposes it is easier to use some other torrent all-in-one prorgam, like qBittorrent.

**Comment by Pentaphon** [comment]
> For this purposes it is easier to use some other torrent all-in-one program, like qBittorrent.

With all due respect, I disagree. 

1) The exe can be closed with the same way it was opened: with a close.bat file in the folder it was running from. I think people would get this impression from transmission-vs but it isn't that simple. I think making it that simple would add to transmission-vs's utility since a user would get 1 click on-off. 

2) With a silent transmission-daemon.exe you aren't waiting for a GUI to load but it's just as simple to use with any frontend. It brings a different, ultra low-resource experience to Windows users who usually just have one option and that's the normal install. It's a niche that I think is worth filling and you would take it further by offering a completely Windows-native solution to an easy, silent daemon that doesn't require a service to be set up. Just a single click.

**Comment by depler** [comment]
May be some day, not now. So far `transmission-vs` is not popular, so it's kind of personal project. Anyway, feel free to create `one_click_gui.bat` which will run hidden daemon and your favorite GUI, if you really need this.

**Comment by Pentaphon** [comment]
> May be some day, not now. So far `transmission-vs` is not popular, so it's kind of personal project. Anyway, feel free to create `one_click_gui.bat` which will run hidden daemon and your favorite GUI, if you really need this.

Sadly, I don't have the skills to create that for myself. Also, I was hoping that including such a simple way to run this daemon would make it popular with users. Simple solutions usually attract users pretty easily.
