### ISSUE TITLE
Include Official Web-UI?

### ISSUE THREAD

**Issue by Pentaphon** [depler/transmission-vs#3]
I'm not a big fan of Transmissionic because it's way too huge on a desktop web browser (it seems more suited for a small touchscreen than a full desktop browser with mouse) and I like the progress being made on 4.0's web-ui which is better adapted for desktop use. Any chance we can have the original web-ui included in the package? Or maybe even an easy way to switch between the original web-ui and transmissionic? 

I can see a lot of people on Windows asking for the original web-ui since they are more likely to use the original web-ui than Transmissionic, which isn't very well-known in the Transmission community. 

Transmissionic is already easy to download from their Github and place in the folder to replace the original web-ui but it's not that easy for Windows users to have to install Transmission, extract the web folder from the installation folder, uninstall the unnecessary and redundant Transmission installation...so in terms of making it easier for Windows users to access the original web-ui, please include the original web-ui somehow. Thanks.

**Comment by depler** [comment]
Sorry, there are no plans to replace `transmissionic` UI with default one. This is just a matter of taste which UI is better for you, and you can easily replace it just by coping files. Personally I prefer `transmissionic` by multiple reasons, and this is only my pet project with very limited popularity.
