### ISSUE TITLE
Remove TRANSMISSION_WEB_HOME from environment variables when deleting service

### ISSUE THREAD

**Issue by Pentaphon** [depler/transmission-vs#4]
Hi, I got this weird error after using transmission-vs and removing it so I can use the new Transmission 4.0.0 beta 3

1) I removed the transmission-vs service per the instructions on the README and deleted the transmission-vs folder. 
2) Removed any app data that might have been left behind to be sure I got a clean install of 4.0.0 beta 3
3) Installed Transmission 4.0.0 beta 3 to try the new web-UI and help test
4) When I pressed Remote > Open web client on 4.0.0 beta 3, I get the following on my Firefox: 
```
404: Not Found
C:\Transmission\web/index.html (The system cannot find the path specified.)
```

This is NOT where Transmission 4.0.0 beta 3 is installed, but rather, where I put my Transmission-vs folder, which also made a C:\Torrents folder. 

Why is 4.0.0 beta 3 pointing to where I had the transmission-vs web-UI? 

Is this a remnant somewhere stuck in the registry after installing transmission-vs as a service? 

I am not able to connect to the web-UI on 4.0.0 beta 3 because of this. 

Since it's pointing to where I had my transmission-vs folder, is this due to something transmission-vs left behind? Please advise.

**Comment by depler** [comment]
Hi, you need to change/remove `TRANSMISSION_WEB_HOME` environment variable

**Comment by depler** [comment]
Yes, it is set automatically when you run `service_create.bat`. I will fix it in future, it should be deleted with service.

**Comment by Pentaphon** [comment]
> Yes, it is set automatically when you run `service_create.bat`. I will fix it in future, it should be deleted with service.

Ah, glad to hear that is unintended behavior. About time I find an issue that actually needs a fix. Thanks for the quick response.

**Comment by Pentaphon** [comment]
@depler could you make this happen for 4.0.0?

**Comment by depler** [comment]
Sorry, there is no easy way to delete environment variable in Windows. Need some research in future.

**Comment by Pentaphon** [comment]
> Sorry, there is no easy way to delete environment variable in Windows (thank you, Microsoft). Need some research in future.

Maybe not create it so it doesn't conflict with the original client?

**Comment by depler** [comment]
Without creating it - transmission doesn't know where to search web UI files, so it will not work as portable executable

**Comment by Pentaphon** [comment]
> Without creating it - transmission doesn't know where to search web UI files, so it will not work as portable executable

I currently use this to run a portable daemon on Windows. It's similar to your project, but it never gave me this issue. Perhaps it will give you more information to solve this issue. I'd love to switch to yours since it is using 4.0.0 instead of the old 2.77 code. 

https://sourceforge.net/projects/transmissiondaemon/

**Comment by depler** [comment]
I've fixed this. No more `TRANSMISSION_WEB_HOME` variable in scripts, using `public_html` subfolder instead.

**Comment by Pentaphon** [comment]
Thanks! Really appreciate it.
